services:
  - type: web
    name: market-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: ALPHAVANTAGE_KEY
        sync: false
      - key: FINNHUB_KEY
        sync: false
      - key: KEEP_ALIVE
        value: "True"
      - key: KEEP_ALIVE_INTERVAL
        value: "150"
      - key: MAX_NEWS_AGE_HOURS
        value: "2"
